export const validatePathFolder = (pathFolder: string) => {
  const blackList = [
    '..',
    '\\\\..',
    '\\..',
    'etc',
    'bin',
    'boot',
    'dev',
    'lib',
    'lib64',
    'lost+found',
    'media',
    'mnt',
    'opt',
    'proc',
    'root',
    'run',
    'sbin',
    'srv',
    'sys',
    'tmp',
    'usr',
    'var',
    'initrd.img',
    'vmlinuz',
    'vmlinuz.old',
    'initrd.img.old',
    'snap',
    'home',
    'cdrom',
    'lib32',
    'libx32',
    'srv',
    'snap',
    'bin',
    'sbin',
    'lib',
    'lib64',
    'libx32',
    'usr',
    'sbin',
    'bin',
    'lib',
    'lib64',
    'libx32',
    'usr',
    'sbin',
    'bin',
    'lib',
    'lib64',
    'libx32',
    'usr',
    'sbin',
    'bin',
    'lib',
    'lib64',
    'libx32',
    'usr',
    'sbin',
    'bin',
    'lib',
    'lib64',
    'libx32',
    'usr',
    'sbin',
    'bin',
    'lib',
    'lib64',
    'libx32',
    'usr',
    'sbin',
    'bin',
    'lib',
    'lib64',
    'libx32',
    'usr',
    'sbin',
    'bin',
    'lib',
    'lib64',
    'libx32',
    'usr',
    'sbin',
    'bin',
    'lib',
    'lib64',
    'libx32',
    'usr',
    'sbin',
    '%5c..',
    '%c0%af',
    '%252e',
  ];

  const pathFolderSplit = pathFolder.split('/');
  const pathFolderSplitLength = pathFolderSplit.length;

  for (let i = 0; i < pathFolderSplitLength; i++) {
    if (blackList.includes(pathFolderSplit[i])) {
      console.log('blacklist: ', pathFolderSplit[i]);
      return false;
    }
  }

  return true;
};
